# Generated by Django 2.2.4 on 2019-08-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='Date')),
                ('open', models.DecimalField(blank=True, decimal_places=2, help_text='Open', max_digits=10)),
                ('high', models.DecimalField(blank=True, decimal_places=2, help_text='High', max_digits=10)),
                ('close', models.DecimalField(blank=True, decimal_places=2, help_text='Close', max_digits=10)),
                ('low', models.DecimalField(blank=True, decimal_places=2, help_text='Low', max_digits=10)),
                ('volume', models.IntegerField(blank=True, help_text='Volume')),
                ('code', models.CharField(default=False, help_text='Code', max_length=150)),
            ],
        ),
    ]
